### PR TITLE
Site upgrade

### PR DESCRIPTION
**Pull request by xmunoz**
They rewrote the whole site as a .net app and now the scraper is broken. Plus shizz was hella outdated so this PR upgrades everything and scrapes the new site.

### CODE REVIEW

**Comment by xmunoz** [comment]
Something is wrong with express. Requests are timing out and a lot of the backtrace is highlighted red in the console (bad?). Could you take a look @whroman?
```
$ DEBUG=express* node app/index.js
[...]
Now watching connections to port 3000...
  express:router:route new '/' +12ms
  express:router:layer new '/' +0ms
  express:router:route get '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/logout' +1ms
  express:router:layer new '/logout' +0ms
  express:router:route get '/logout' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/update' +0ms
  express:router:layer new '/update' +0ms
  express:router:route post '/update' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/delete' +0ms
  express:router:layer new '/delete' +0ms
  express:router:route post '/delete' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/auth/google' +0ms
  express:router:layer new '/auth/google' +1ms
  express:router:route get '/auth/google' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/auth/google' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/auth/google/callback' +0ms
  express:router:layer new '/auth/google/callback' +0ms
  express:router:route get '/auth/google/callback' +0ms
  express:router:layer new '/' +1ms
  express:router:route get '/auth/google/callback' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:region' +5ms
  express:router:layer new '/:region' +0ms
  express:router:route get '/:region' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:region/next-week' +1ms
  express:router:layer new '/:region/next-week' +0ms
  express:router:route get '/:region/next-week' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:region/all' +0ms
  express:router:layer new '/:region/all' +0ms
  express:router:route get '/:region/all' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/:region/implausible' +0ms
  express:router:layer new '/:region/implausible' +0ms
  express:router:route get '/:region/implausible' +0ms
  express:router:layer new '/' +0ms
  express:router dispatching GET / +12s
  express:router query  : / +1ms
  express:router expressInit  : / +1ms
  express:router urlencodedParser  : / +1ms
  express:router cookieParser  : / +0ms
  express:router methodOverride  : / +0ms
  express:router clientSession  : / +1ms
  express:router initialize  : / +1ms
  express:router authenticate  : / +0ms
  express:view require "jade" +31ms
```

**Comment by xmunoz** [comment]
I've worked through the above issue. Now the problem appears to be ngTable. Start up the app, load the homepage, and check the browser console for debugging deets.

```
Error: [$injector:nomod] Module 'ngTable' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

ng-table appears to be installed however...i did upgrade it so it's probably related to that.

**Comment by whroman** [comment]
@xmunoz I had slightly different issues with getting the express server to serve the frontend. I resolved these in my local env, so please try in yours. I made a change to the npm dependencies, so please run `npm install` before testing again.

**Comment by xmunoz** [comment]
Yay! Yeah, I worked through the ngtable issues (commits above). It looks like your commits also fixed a couple of things. This frontend refactor whack-a-mole game is almost over. I updated prod and was able to start the server, log in with google oauth, and see the homepage. There are still some errors though. 

```
angular.js:14791 TypeError: _.findWhere is not a function
    at Object.<anonymous> (listings.js:28)
    at Object.invoke (angular.js:5097)
    at $controllerInit (angular.js:11067)
    at nodeLinkFn (angular.js:9930)
    at compositeLinkFn (angular.js:9239)
    ...
```

Feel free to #yolo debug on prod. I killed forever (the process manager) and disabled the cron job, so you will need to start the server manually to debug.

```
cristina@tinta:~/ALLegalsScraper$ nvm use
cristina@tinta:~/ALLegalsScraper$ node app/index.js
```

**Comment by xmunoz** [comment]
Ok, this is just about ready. @whroman could you take a look at these final two scraper issues:
1. This isn't configured to iterate right now (only does one county)
2. It hangs on the db insert promise thing. Can you figure out why?
```
cristina@tinta:~/ALLegalsScraper/scraper$ node index.js 
sleep: using busy loop fallback
Scraping county: 24
=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
Fetched all results!
5 listings were scraped.
Commencing DB inserts for following listings, which were not found in our DB.
437145, 437159, 437162, 1830103, 1830568
```

**Comment by whroman** [comment]
@xmunoz  status update: scraping an array of counties and writing them to the database *appears* to work now. i ran `npm run scraper` successfully for an array of only two counties on prod. however, more thorough testing needs to occur before we call it a day. the data on alabamapublicnotices still needs to be cross-checked against the rows that are being inserted into the `foreclosures` table. ill prioritize this and do it sometime this weekend.

**Comment by xmunoz** [comment]
There were a few more bugs. Now it runs more or less ok, but after a couple of successful inserts, it spit out this error:
```
Commencing insertion for Foreclosure #1833161
TypeError: Cannot read property 'replace' of undefined
    at _class16._escapeValue (/home/cristina/ALLegalsScraper/node_modules/squel/dist/squel.js:433:66)
    at _class16._formatValueForQueryString (/home/cristina/ALLegalsScraper/node_modules/squel/dist/squel.js:593:39)
    at _class16._buildString (/home/cristina/ALLegalsScraper/node_modules/squel/dist/squel.js:710:36)
    at _class16._toParamString (/home/cristina/ALLegalsScraper/node_modules/squel/dist/squel.js:1886:28)
    at /home/cristina/ALLegalsScraper/node_modules/squel/dist/squel.js:2837:20
    at Array.map (<anonymous>)
    at _class47._toParamString (/home/cristina/ALLegalsScraper/node_modules/squel/dist/squel.js:2836:40)
    at _class47.toString (/home/cristina/ALLegalsScraper/node_modules/squel/dist/squel.js:797:21)
    at /home/cristina/ALLegalsScraper/scraper/scrapeCounties.js:233:30
    at _fulfilled (/home/cristina/ALLegalsScraper/node_modules/q/q.js:854:54)
```

**Comment by xmunoz** [comment]
Problem appears to be poor handling of a parsing error of a particular listing:

```
Commencing insertion for Foreclosure #1833161
{ body: 'MORTGAGE FORECLOSURE SALE Default having been made in the payment of the indebtedness secured by that certain mortgage executed by Maximilian A. Oliver, a single male, originally in favor of Mortgage Electronic Registration Systems, Inc., as nominee for Platinum Mortgage, Inc., on the 31st day of October, 2011, said mortgage recorded in the Office of the Judge of Probate of Madison County, Alabama, in Instrument No. 20111115000617080; the undersigned Wells Fargo Bank, N.A., as Mortgagee/Transferee, under and by virtue of the power of sale contained in said mortgage, will sell at public outcry to the highest bidder for cash, in front of the main entrance of the Courthouse at Huntsville, Madison County, Alabama, on December 29, 2017, during the legal hours of sale, all of its right, title, and interest in and to the following described real estate, situated in Madison County, Alabama, to-wit: Lot 2, Block 2, according to the map of survey of Green Cove Meadows, Second Addition, as the same appears of record in the Office of the Judge of Probate of Madison County, Alabama, in Plat Book 10, Page 77. Property street address for informational purposes: 14029 Armond Dr SW, Huntsville, AL 35803 THIS PROPERTY WILL BE SOLD ON AN "AS IS, WHERE IS" BASIS, SUBJECT TO ANY EASEMENTS, ENCUMBRANCES, AND EXCEPTIONS REFLECTED IN THE MORTGAGE AND THOSE CONTAINED IN THE RECORDS OF THE OFFICE OF THE JUDGE OF PROBATE OF THE COUNTY WHERE THE ABOVE-DESCRIBED PROPERTY IS SITUATED. THIS PROPERTY WILL BE SOLD WITHOUT WARRANTY OR RECOURSE, EXPRESSED OR IMPLIED AS TO TITLE, USE AND/OR ENJOYMENT AND WILL BE SOLD SUBJECT TO THE RIGHT OF REDEMPTION OF ALL PARTIES ENTITLED THERETO. Alabama law gives some persons who have an interest in property the right to redeem the property under certain circumstances. Programs may also exist that help persons avoid or delay the foreclosure process. An attorney should be consulted to help you understand these rights and programs as a part of the foreclosure process. This sale is made for the purpose of paying the indebtedness secured by said mortgage, as well as the expenses of foreclosure. The successful bidder must tender a non-refundable deposit of Five Thousand Dollars ($5,000.00) in certified funds made payable to Sirote & Permutt, P.C. at the time and place of the sale. The balance of the purchase price must be paid in certified funds by noon the next business day at the Law Office of Sirote & Permutt, P.C. at the address indicated below. Sirote & Permutt, P.C. reserves the right to award the bid to the next highest bidder should the highest bidder fail to timely tender the total amount due. The Mortgagee/Transferee reserves the right to bid for and purchase the real estate and to credit its purchase price against the expenses of sale and the indebtedness secured by the real estate. This sale is subject to postponement or cancellation. Wells Fargo Bank, N.A., Mortgagee/Transferee PUBLICATION DATES: October 20, 2017, October 27, 2017, November 3, 2017and January 31, 2018 NEWSPAPER: The Huntsville Times The above mortgage foreclosure sale has been postponed until 02/09/2018 during the legal hours of sale in front of the main entrance of the courthouse in the City of Huntsville, Madison County, Alabama. Ginny Rutledge SIROTE & PERMUTT, P.C. P. O. Box 55727 Birmingham, AL 35255-5727 Attorney for Mortgagee/Transferee www.sirote.com/foreclosures 422301 Huntsville Times: January 31, 2018',
  case_id: 1833161,
  county: 'Madison',
  source: 'Huntsville Times',
  pub_date: '2018-01-31',
  city: 'Madison County',
  street_addr: 'The Huntsville Times The above mortgage foreclosure sale has be',
  zip: undefined,
  name1: 'Maximilian',
  sale_date: '2018-02-09' }
TypeError: Cannot read property 'replace' of undefined
```

**Comment by xmunoz** [comment]
So I believe the problem now is that it's scraping the same results over and over. Each iteration takes cumulatively more time because it goes back and starts at the beginning. Here is my best guess for where the problem is but tbh I don't understand 90% of your rewrite.

```
    const scrapedCounties = counties.reduce((acc, countyID) => (
        acc.then(() =>
            scrapeCounty(countyID).then((foreclosures) => writeToDB(foreclosures))
        )
    ), Promise.resolve())
```

You can see the problem in the following log output:
```
cristina@tinta:~/ALLegalsScraper$ npm run scraper

> allegalsscraper@1.0.0 scraper /home/cristina/ALLegalsScraper
> node scraper/index.js

sleep: using busy loop fallback
5 entries were found.
Scraping from target site complete.
=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
Result! ID #1830569
Result! ID #1833409
Result! ID #1833411
Result! ID #1833521
Result! ID #1834429
No new results were scraped
Scraped Listings: 5
Inserted Rows: 0
Duplicates Found: 0
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
5 entries were found.
5 entries were found.
Scraping from target site complete.
=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
Result! ID #1830569
Result! ID #1833409
Result! ID #1833411
Result! ID #1833521
Result! ID #1834429
No new results were scraped
Scraped Listings: 5
Inserted Rows: 0
Duplicates Found: 0
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
5 entries were found.
5 entries were found.
5 entries were found.
Scraping from target site complete.
=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
Result! ID #1833411
Result! ID #1833521
Result! ID #1834429
Result! ID #1834237
Result! ID #1834238
No new results were scraped
Scraped Listings: 5
Inserted Rows: 0
Duplicates Found: 0
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
```

**Comment by whroman** [comment]
@xmunoz 

I managed to resolve the issue where every preceding county was being run as the county list was being looped. I did this by shifting `xvfb` and `nightmare` to initialize and teardown for each individual county. It seems to work, but I came across an error for Jefferson County, #36. A related issue is that the scraper process doesnt exit or continue when this error is thrown.

I'll try to the resolve the second issue first. I may have a bit of time to look at this tonight.

The `body` property for this foreclosure's json seems reasonable to me. Any ideas how that could be making the DB insertion for it fail?

Error:
```
Commencing insertion for Foreclosure #1249142
{ Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF4\x80\x81\x99Mi...' for column 'body' at row 1
    at Query.Sequence._packetToError (/home/cristina/ALLegalsScraper/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/home/cristina/ALLegalsScraper/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/cristina/ALLegalsScraper/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/cristina/ALLegalsScraper/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/cristina/ALLegalsScraper/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/cristina/ALLegalsScraper/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
```

The JSON for Foreclosure #1249142:
```
{
    body: '|Case No. 17BHM02181NOTICE TO NON-RESIDENTS TO PROBATE WILLState of Alabama, Jefferson CountyProbate CourtESTATE OF:  DONALD ROY JONES, DECEASED\tOn the 8TH day of September, 2017, came Cynthia Dodd and filed her petition in writing therewith producing and filing in this Court an instrument of writing purporting to be the last will and testament of Donald Roy Jones, Deceased, and praying for such orders decrees and proceedings as will duly and legally effect the Probate and record of said instrument as such will.\tAnd the 20th day of February, 2018, at 2:00 P.M., having been set as a day for hearing said petition and the proof to be submitted in support of same and it further appearing that the following next of kin of said deceased are: viz:\tChristopher Mark Burson and All Unknown Heirs, whose names, ages, conditions and whereabouts are unknown\tIt is therefore ordered that notice of the filing of said petition and of the day set for hearing same be given by publication once a week for three successive weeks in the Alabama Messenger, a newspaper published in Jefferson Co., Al.  Notice is hereby given the said named next of kin and all other persons in interest, to be and appear in this Court on said 20th day of February, 2018, to contest said petition if they think proper so to do.Done this the 19th day of January, 2018.Sherri C. Friday, Judge of ProbateAla.Ms.- Jan. 20, 27, Feb. 3, 2018|CASE NO. 2016-227871NOTICE OF SALE OF LAND FOR DIVISION AND DISTRIBUTION/PAYMENT DEBTSState of Alabama, Jefferson CountyProbate CourtESTATE OF:  JAMES E. MARSH JR., DECEASED\tOn the 3RD day of January, 2018, came David G. Marsh, the Executor, for the Estate of James E. Marsh Jr., Deceased, and filed his petition in writing, praying for the sale of certain lands described as follows:\t6520 Pinewood Drive, Pinson, AL 35126 (Parcel ID #09-00-31-1-003-009.000)\tSaid property belonging to said estate, the sale being for the purpose of paying debts and or division and distribution among the heirs and devisees, upon the grounds that said property cannot be equitable divided among the joint owners (or that personal property is insufficient therefore) and it appearing to the Court from said petition that the following heirs are non-residents of the State of Alabama:\tAny and All Unknown Heirs and Creditors, whose names, ages, conditions and addresses are unknown\tAnd whereas the 7th day of February, 2018, at 3:30 P.M., has been set as a day for hearing said petition and the testimony to be submitted in support of same.\tIt is therefore ordered that notice of the filing of said petition and of the day set for hearing same be given by publication once a week for three successive weeks in the Alabama Messenger, a newspaper published in this County, notifying all parties in interest to appear and contest said petition if they think proper so to do.This the 18th day of January, 2018.Sherri C. Friday, Judge of ProbateAla.Ms.- Jan. 20, 27, Feb. 3, 2018|CASE NO. 2016-227871NOTICE OF SALE OF LAND FOR DIVISION AND DISTRIBUTION/PAYMENT DEBTSState of Alabama, Jefferson CountyProbate CourtESTATE OF:  JAMES E. MARSH JR., DECEASED\tOn the 3RD day of January, 2018, came David G. Marsh, the Executor, for the Estate of James E. Marsh Jr., Deceased, and filed his petition in writing, praying for the sale of certain lands described as follows:\t1311 2nd Street NW, Birmingham, AL 35215 Parcel ID #12-00-19-010-011.000\tSaid property belonging to said estate, the sale being for the purpose of paying debts and or division and distribution among the heirs and devisees, upon the grounds that said property cannot be equitable divided among the joint owners (or that personal property is insufficient therefore) and it appearing to the Court from said petition that the following heirs are non-residents of the State of Alabama:\tAny and All Unknown Heirs and Creditors, whose names, ages, conditions and addresses are unknown\tAnd whereas the 7th day of February, 2018, at 3:30 P.M., has been set as a day for hearing said petition and the testimony to be submitted in support of same.\tIt is therefore ordered that notice of the filing of said petition and of the day set for hearing same be given by publication once a week for three successive weeks in the Alabama Messenger, a newspaper published in this County, notifying all parties in interest to appear and contest said petition if they think proper so to do.This the 18th day of January, 2018.Sherri C. Friday, Judge of ProbateAla.Ms.- Jan. 20, 27, Feb. 3, 2018|CASE NO. 2015-225884NOTICE OF PUBLICATION ON FINAL SETTLEMENTState of Alabama, Jefferson CountyProbate CourtESTATE OF: JOE T. PHILLIPS, JR., AKA JOE THOMAS PHILLIPS, JR., DECEASED.To: 􀁙Misty Phillips Raglan11780 Wellsley WayAlpharetta, GA 30005and all other parties interested in said estate, take notice;\tOn the 18th day of October 2017, came Elizabeth W. McElroy, the Administrator ad Colligendum of the Estate of Joe T. Phillips, Jr., Aka Joe Thomas Phillips, Jr. , Deceased, and filed her accounts, vouchers, evidence and statement for a Final Settlement of same.\tIt is therefore ordered that the 22nd day of February 2018, at 2:30 P.M., be appointed a day for making such settlement at which time all parties in interest can appear and contest the same if they think proper.This the 18th day of January, 2018.Sherri C. Friday, Judge of ProbateAla.Ms.- Jan. 20, 27, Feb. 3, 2018|Case No. 18BHM00084NOTICE TO CREDITORSIn the Probate Court of Jefferson County, AlabamaIn the matter of the Estate of: JAMES M. KING, JR., a/k/a, JAMES MURRAY KING, JR., Deceased\tLetters Testamentary upon last will and testament of said decedent, having been granted to the undersigned on the 11th day of January, 2018, by the Honorable Alan L. King, Judge of the Probate Court of Jefferson County, Alabama, notice is hereby given that all persons having claims against said Estate are required to file an itemized and verified statement of such claim in the office of the said Judge of Probate within six months from above date, or said claim will be barred and payment prohibited. PAUL JAYNES\tPersonal RepresentativeAla. Ms. Jan. 20, 27, Feb. 3, 2018|Case No. 18BHM00086NOTICE TO CREDITORSIn the Probate Court of Jefferson County, AlabamaIn the matter of the Estate of: THOMAS E. ESTRIDGE a/k/a, THOMAS ERWIN ESTRIDGE., Deceased\tLetters Testamentary upon last will and testament of said decedent, having been granted to the undersigned on the 12th day of January, 2018, by the Honorable Alan L. King, Judge of the Probate Court of Jefferson County, Alabama, notice is hereby given that all persons having claims against said Estate are required to file an itemized and verified statement of such claim in the office of the said Judge of Probate within six months from above date, or said claim will be barred and payment prohibited. RONALD ESTRIDGE\tPersonal RepresentativeAla. Ms. Jan. 20, 27, Feb. 3, 2018|Case No. 18BHM00031NOTICE TO CREDITORSIn the Probate Court of Jefferson County, AlabamaIn the matter of the Estate of: WILLIAM FRANK MCCALL., Deceased\tLetters Testamentary upon last will and testament of said decedent, having been granted to the undersigned on the 18th day of January, 2018, by the Honorable Sherri C. Friday, Judge of the Probate Court of Jefferson County, Alabama, notice is hereby given that all persons having claims against said Estate are required to file an itemized and verified statement of such claim in the office of the said Judge of Probate within six months from above date, or said claim will be barred and payment prohibited. MARTHA MCCALL and FRANCES BETSY E. RICE\tPersonal RepresentativesAla. Ms. Jan. 20, 27, Feb. 3, 2018|Case No. 18BHM00085NOTICE TO CREDITORSIn the Probate Court of Jefferson County, AlabamaIn the matter of the Estate of: WILLIAM C. TAYLOR, a/k/a, WILLIAM CALVIN TAYLOR, Deceased\tLetters of Administration upon the Estate, of said decedent, having been granted to the undersigned on the 12th day of January, 2018, by the Honorable Sherri C. Friday, Judge of the Probate Court of Jefferson County, Alabama, notice is hereby given that all persons having claims against said Estate are required to file an itemized and verified statement of such claim in the office of the said Judge of Probate within six months from above date, or said claim will be barred and payment prohibited. LOIS F. TAYLOR\tPersonal RepresentativeAla. Ms. Jan. 20, 27, Feb. 3, 2018|Case No. 18BHM00089NOTICE TO CREDITORSIn the Probate Court of Jefferson County, AlabamaIn the matter of the Estate of: RAYMOND ALLEN BARNETT, Deceased\tLetters of Administration upon the Estate, of said decedent, having been granted to the undersigned on the 12th day of January, 2018, by the Honorable Sherri C. Friday, Judge of the Probate Court of Jefferson County, Alabama, notice is hereby given that all persons having claims against said Estate are required to file an itemized and verified statement of such claim in the office of the said Judge of Probate within six months from above date, or said claim will be barred and payment prohibited. BRENDA G. BARNETT\tPersonal RepresentativeAla. Ms. Jan. 20, 27, Feb. 3, 2018|Case No. 18BHM00103NOTICE TO CREDITORSIn the Probate Court of Jefferson County, AlabamaIn the matter of the Estate of: DARREL DARDEN, Deceased\tLetters of Administration upon the Estate, of said decedent, having been granted to the undersigned on the 17th day of January, 2018, by the Honorable Sherri C. Friday, Judge of the Probate Court of Jefferson County, Alabama, notice is hereby given that all persons having claims against said Estate are required to file an itemized and verified statement of such claim in the office of the said Judge of Probate within six months from above date, or said claim will be barred and payment prohibited. EVELYN DARDEN BOYKINS\tPersonal RepresentativeAla. Ms. Jan. 20, 27, Feb. 3, 2018|Case No. 18BHM00113NOTICE TO CREDITORSIn the Probate Court of Jefferson County, AlabamaIn the matter of the Estate of: JAMES RAYMOND CORMANY, JR., Deceased\tLetters of Administration upon the Estate, of said decedent, having been granted to the undersigned on the 19th day of January, 2018, by the Honorable Sherri C. Friday, Judge of the Probate Court of Jefferson County, Alabama, notice is hereby given that all persons having claims against said Estate are required to file an itemized and verified statement of such claim in the office of the said Judge of Probate within six months from above date, or said claim will be barred and payment prohibited. SUSAN CORMANY ANGELO\tPersonal RepresentativeAla. Ms. Jan. 20, 27, Feb. 3, 2018|',
    caseId: '1249142',
    county: 'Jefferson',
    link: 'Details.aspx?SID=k1dwicic01c3y5nrrzn4dvca&ID=1249142',
    pubDate: 'February 03, 2018',
    source: 'Alabama Messenger'
}
```

**Comment by xmunoz** [comment]
I can deal with the parser issue, which is what it looks like this is. ty!

**Pull request merged**
